### ISSUE TITLE
spectrum_analysis early layers bias

### ISSUE THREAD

**Issue by MatoFD** [hasanferit/DeepFault#4]
Hello,

I am a research intern trying to find properties of DeepFault's results. In doing this, the selection of suspicious neurons made me pause.

Here is the original code:
```
    relevant_vals = sorted(flat_scores, reverse=True)[:suspicious_num]

    suspicious_neuron_idx = []
    for i in range(len(scores)):
        for j in range(len(scores[i])):
            if scores[i][j] in relevant_vals:
                if trainable_layers == None:
                    suspicious_neuron_idx.append((i,j))
                else:
                    suspicious_neuron_idx.append((trainable_layers[i],j))
            if len(suspicious_neuron_idx) == suspicious_num:
                break

    return suspicious_neuron_idx
```

Multiple neurons can have the same "edge" score, where neurons with a higher score are suspicious but a lower score is not suspicious. In this case, a neuron with a higher score which is in a deeper layer will not be included in suspicious_neuron_idx.

Here is my modification attempt:
```
flat_indexes = np.argpartition(flat_scores, -suspicious_num)[-suspicious_num:]

    suspicious_neuron_idx = []
    for idx in flat_indexes:
        # unflatten idx
        i = 0
        while idx >= len(scores[i]):
            idx -= len(scores[i])
            i += 1
        j = idx

        if trainable_layers is None:
            suspicious_neuron_idx.append((i, j))
        else:
            suspicious_neuron_idx.append((trainable_layers[i], j))

    return suspicious_neuron_idx
```

**Comment by hfeniser** [comment]
Hi, thanks for your interest!

Selecting neurons from earlier layers first should not harm the correctness. One could start searching from the top layer if upper layer neurons are more preferable. Since the number of suspicious neurons is bounded strictly by the user one has to make a choice.

I had no chance to test to the proposed script but I am not sure if it works as desired. If I understand correctly, `flat_indexes` should not correspond to actual neuron indexes. Because `flat_scores` is nothing but a list of suspiciousness scores and does not contain any information regarding to the positions of neurons.

**Comment by MatoFD** [comment]
I agree that since the number is strictly bounded there is no problem to chose earlier layers over deeper ones, but I still think using relevant_vals is a problem if there are repeated scores. 

Here is an example to illustrate my point:
suspicious_num = 5
scores = [[1.0, 0.9, 0.0]
                [0.0, 0.0, 0.0]
                [1.0, 0.9, 0.0]
                ]
In this example relevant_vals will be [1.0, 1.0, 0.9, 0.9, 0.0]
I would expect suspicious_neurons_idx to be [(0,0), (0,1), (0,2), (2,0), (2,1)]
But the result will be [(0,0), (0,1), (0,2), (1,0), (1,1)], ignoring some big scores in the last layer.
(Actually the break only breaks the "j" loop with continues the "i" loop, so the result when tested returns more than 5 suspicious_idx, I imagine this is not intended)

Regarding the proposed script, from what I understand of the code and my experiments, since 
`flat_scores = [float(item) for sublist in scores for item in sublist if not math.isnan(float(item))]`
then the order of elements in flat_scores will be the same as if we traverse scores like
```
for i in range(len(scores))
    for j in range(len(scores[i]))
```
So if we use argpartition we know that all elements in flat_indexes are flattened indexes of neurons with one of the higher scores, Is this interpretation incorrect? Still, this was only an idea, and I understand if there is a better workaround, but I still think the previous example is a bug.

Thanks for your time.

**Comment by hfeniser** [comment]
Hi again!
Yes, I think you are correct and thanks for spotting this error. I also agree that `argpartition` might be the solution here. May be you could create a pull request with your implementation and then we can merge it to the main branch.

**Comment by MatoFD** [comment]
There it goes! I refactored the file so all three scoring methods call a single function that has the main change discussed above.

There was also a bug in the logic here:
```
i = 0
while idx >= len(scores[i]):
    idx -= len(scores[i])
    i += 1
j = idx
```
that is fixed in the pull request.

This is my first pull request, so please let me know if it has any problem.

**Comment by hfeniser** [comment]
Thanks, merged it.
