### ISSUE TITLE
How do I add new dataset to the code?

### ISSUE THREAD

**Issue by Deepakgthomas** [hasanferit/DeepFault#8]
I enjoyed reading your paper and running your code. I wondered how I could run your code with my custom dataset. Going into your utils.py file, I see the functions load_CIFAR and load_MNIST. Would it be enough to modify these functions? Thank you.

**Comment by gerasimou** [comment]
Yes, that should be sufficient @Deepakgthomas 
(of course, you would need to have trained your DNN model using the training set from your custom dataset).
